name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Upload files to server
      run: |
        scp -r ./* ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/root/silverbot

    - name: Deploy on server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          set -ex

          # Navigate to the directory
          cd /root/silverbot

          # Stop the running container
          docker stop sbotc || true

          # Remove the container
          docker rm sbotc || true

          # Delete old Docker image
          docker rmi -f sboti || true

          # Build new Docker image
          docker build -t sboti .

          # Run the container
          docker run -d --name sbotc sboti
        EOF